name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
      run: flutter build web --release

      - name: Deploy to Netlify
        uses: nwtgck/netlify-deploy-action@v1
        with:
          netlify-api-token: ${{ secrets.NETLIFY_API_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-folder: build/web
